import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

[window]
opacity = 0.95
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
size = 18

  [font.normal]
  family = "0xProto Nerd Font"
  style = "Regular"

[scrolling]
history = 100000
